### ISSUE TITLE
KeyError: 'API_KEY' When Running run.sh

### ISSUE THREAD

**Issue by jandrusk** [jpsutton/logrhythm-proofpoint-on-demand#1]
First, thanks for writing this code. I decided to give this code a shot since it seems to achieve a use case we are looking at leveraging.

I'm getting the following error when running the run.sh bash script:

**Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 32, in main
    p_client = Process(target=ppod_client, args=(log_queue, config['ppod_client']['API_KEY'], exit_flag))
  File "/usr/lib64/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'API_KEY'
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)**

Does this mean the API key is invalid?

**Comment by jpsutton** [comment]
Hi Justin,

That looks like a refactoring bug on my part. I've updated main.py to reference the correct config.ini entry of "API_TOKEN" rather than "API_KEY".

Please also make sure you've copied the config.ini.example to config.ini and modified to match your environment.

Regards,
Jared

**Comment by jpsutton** [comment]
One more thing I noticed while reviewing this code: in ppod_client.py, it looks like I failed to make a config element for the "cid" portion of the URL that's built. You'll need to replace "YOUR_CID_HERE" with the cid for your own hosted environment.

**Comment by jandrusk** [comment]
Thanks for the quick response, @jpsutton Now I'm getting a bunch of 401's. Would that indicate a permissions issue with the key?

**Comment by jpsutton** [comment]
Yes, an HTTP 401 is "Unauthorized", which generally means it's a credential / API Key issue.
